name: Sync File to Selected Targets

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v2
      with:
        repository: yale-redcap/yes3-powershell-scripts
        ref: main
        path: source-repo

    - name: Set up Git
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

    - name: Install GitHub CLI
      run: |
        curl -L https://github.com/cli/cli/releases/download/v2.22.1/gh_2.22.1_linux_amd64.tar.gz -o ghcli.tar.gz
        tar -xzf ghcli.tar.gz
        sudo mv gh_2.22.1_linux_amd64/bin/gh /usr/local/bin/
        rm -rf gh_2.22.1_linux_amd64 ghcli.tar.gz

    - name: Authenticate GitHub CLI
      run: echo "${{ secrets.PC_PAT_ALL_REPOS }}" | gh auth login --with-token

    - name: Copy file to target repo 1
      env:
        PAT: ${{ secrets.PC_PAT_ALL_REPOS }}
      run: |
        set -e # Exit immediately if a command exits with a non-zero status.
        git clone https://x-access-token:${{ secrets.PC_PAT_ALL_REPOS }}@github.com/yale-redcap/yes3-dashboard-docs.git
        cd yes3-dashboard-docs
        branch_name=sync-changes-$(date +%Y%m%d%H%M%S)
        git checkout -b $branch_name
        cp -f ../source-repo/session-install.ps1 .
        git add session-install.ps1
        git commit -m "Sync file from yes3-powershell-scripts repository"
        git push --set-upstream origin $branch_name

        # Create a new pull request and capture the output
        pr_output=$(gh pr create --title "Sync file from yes3-powershell-scripts" --body "Automated sync of session-install.ps1 file." --base main --head $branch_name)

        # Extract the pull request URL
        pr_url=$(echo "$pr_output" | grep -o 'https://github.com/[^\"]*')
        
        # Extract the pull request number from the URL
        pr_number=$(echo $pr_url | awk -F'/' '{print $NF}')
        
        # Add a comment to the pull request
        gh pr comment $pr_number --body "Automatically merged by GitHub Actions."

        # Merge the pull request
        gh pr merge $pr_number --merge

        # cd ..
        # rm -rf yes3-dashboard-docs
