name: Sync File to Targets

on:
  push:
    branches:
      - main

jobs:
  sync-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v2
      with:
        repository: yale-redcap/yes3-powershell-scripts
        ref: main

    - name: Set up Git
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

    - name: Install GitHub CLI
      uses: actions/setup-gh@v2
      with:
        token: ${{ secrets.PC_PAT_ALL_REPOS }}

    - name: Copy file to target repo 1
      env:
        PAT: ${{ secrets.PC_PAT_ALL_REPOS }}
      run: |
        git clone https://x-access-token:${{ secrets.PAT }}@github.com/yale-redcap/yes3-dashboard-docs.git
        cd yes3-dashboard-docs
        branch_name=sync-changes-$(date +%Y%m%d%H%M%S)
        git checkout -b $branch_name
        cp ../xyz.ps1 .
        git add .
        git commit -m "Sync file from yes3-powershell-scripts repository"
        git push --set-upstream origin $branch_name

        # Create a new pull request and merge it
        pr_url=$(gh pr create --title "Sync file from yes3-powershell-scripts" --body "Automated sync of xyz.ps1 file." --base main --head $branch_name --json url --jq '.url')
        pr_number=$(echo $pr_url | awk -F'/' '{print $NF}')
        gh pr merge $pr_number --merge --comment "Automatically merged by GitHub Actions."

        cd ..
        rm -rf yes3-dashboard-docs


    # Add more steps for additional target repositories following the same pattern
